export const WALLET_CREATE_REQUEST = 'WALLET_CREATE_REQUEST';
export const WALLET_CREATE_SUCCESS = 'WALLET_CREATE_SUCCESS';
export const WALLET_CREATE_FAILURE = 'WALLET_CREATE_FAILURE';

export const WALLET_DELETE_REQUEST = 'WALLET_DELETE_REQUEST';
export const WALLET_DELETE_SUCCESS = 'WALLET_DELETE_SUCCESS';
export const WALLET_DELETE_FAILURE = 'WALLET_DELETE_FAILURE';

export const WALLET_UPDATE_REQUEST = 'WALLET_UPDATE_REQUEST';
export const WALLET_UPDATE_SUCCESS = 'WALLET_UPDATE_SUCCESS';
export const WALLET_UPDATE_FAILURE = 'WALLET_UPDATE_FAILURE';

export const WALLET_GET_REQUEST = 'WALLET_GET_REQUEST';
export const WALLET_GET_SUCCESS = 'WALLET_GET_SUCCESS';
export const WALLET_GET_FAILURE = 'WALLET_GET_FAILURE';